# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(blank=True, max_length=100)),
                ('nombre2', models.CharField(blank=True, max_length=100)),
                ('apellido1', models.CharField(blank=True, max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100)),
                ('semestre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('profesor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
